# DSA 504 — Homework 4
## SQL Queries, Joins, and SQL + pandas Integration

**Assigned:** Class 14 (Tuesday, Oct 21)
**Due:** (Monday, Nov 2)
**Worth:** 1 of 6 homework assignments (homework is 50% of your final grade, split evenly across all 6)

> **Instructor note:** this homework's due date needs to be finalized now that the midterm has moved to Oct 28 (originally Class 16's slot). Confirm the new date before distributing.

---

### Instructions

- Use `retail_sales.db` — it must be in the same folder as this notebook. It contains two tables: `sales` (4,014 rows, already cleaned) and `stores` (5 rows, including `Plattsburgh`, which has no matching sales).
- No internet access is required for this assignment.
- Fill in each `# TODO` code cell. Do not delete or reorder cells.
- A few cells ask a short written question — answer directly in the markdown cell provided.
- **AI use:** if you used an AI tool for any part of this assignment, briefly note where and how in the disclosure cell at the bottom, per the course AI-use policy.

### Submission — required step
1. Upload this completed `.ipynb` file directly to the HW4 assignment on Brightspace, and paste the direct link to your `hw4/` folder into the submission comments box.

### Grading breakdown
| Section | Weight |
|---|---|
| Part 1 — Basic Queries | 20% |
| Part 2 — Aggregation | 20% |
| Part 3 — Joins | 25% |
| Part 4 — SQL + pandas Integration | 20% |
| Part 5 — Written Reflection | 15% |

In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("retail_sales (4).db")
print(pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", conn))

     name
0   sales
1  stores

---
## Part 1 — Basic Queries (20%)

**1a.** Write a query that selects `date`, `store`, and `revenue` from `sales` where `revenue` is greater than 4000. Limit to 10 rows.

In [6]:
# TODO 1a
# TODO 1a
query_1a = """
SELECT date, store, revenue
FROM sales
WHERE revenue > 4000
LIMIT 10
"""
df_1a = pd.read_sql_query(query_1a, conn)
df_1a

                  date     store  revenue
0  2025-02-11 00:00:00  Syracuse  5114.40
1  2025-04-13 00:00:00  Syracuse  4157.40
2  2025-10-21 00:00:00    Albany  4201.26
3  2025-03-01 00:00:00     Utica  6814.08
4  2025-11-25 00:00:00  Syracuse  4698.20
5  2025-10-18 00:00:00  Syracuse  5476.72
6  2025-11-02 00:00:00  Syracuse  4918.20
7  2025-10-19 00:00:00      Rome  5440.40
8  2025-09-27 00:00:00      Rome  4152.48
9  2025-08-10 00:00:00      Rome  4721.88

**1b.** Write a query that selects all columns from `sales` where `store` is either `'Rome'` or `'Syracuse'`, using `IN`.

In [7]:
# TODO 1b
query_1b = """
SELECT *
FROM sales
WHERE store IN ('Rome', 'Syracuse')
"""
df_1b = pd.read_sql_query(query_1b, conn)
df_1b

                     date     store  units_sold  revenue     category
0     2025-04-22 00:00:00      Rome        25.0   402.50         toys
1     2025-04-12 00:00:00  Syracuse        38.0  3154.00  electronics
2     2025-02-11 00:00:00  Syracuse        60.0  5114.40  electronics
3     2025-04-10 00:00:00  Syracuse        10.0   147.10         toys
4     2025-03-04 00:00:00      Rome       129.0   807.54    groceries
...                   ...       ...         ...      ...          ...
1995  2025-05-28 00:00:00      Rome        29.0   430.65         toys
1996  2025-01-20 00:00:00      Rome        61.0  1385.31     clothing
1997  2025-05-24 00:00:00  Syracuse        28.0   435.68         toys
1998  2025-08-20 00:00:00      Rome       123.0   825.33    groceries
1999  2025-02-18 00:00:00      Rome        44.0  3953.40  electronics

[2000 rows x 5 columns]

**1c.** Write a query that returns `store`, `category`, and `units_sold`, sorted by `units_sold` descending, limited to the top 5 rows.

In [8]:
# TODO 1c
query_1c = """
SELECT store, category, units_sold
FROM sales
ORDER BY units_sold DESC
LIMIT 5
"""
df_1c = pd.read_sql_query(query_1c, conn)
df_1c

      store   category  units_sold
0  Syracuse  groceries       246.0
1    Albany  groceries       240.0
2      Rome  groceries       228.0
3     Utica  groceries       227.0
4    Albany  groceries       226.0

---
## Part 2 — Aggregation (20%)

**2a.** Write a query that computes total `revenue` per `category`, sorted highest to lowest.

In [9]:
# TODO 2a
query_2a = """
SELECT category, SUM(revenue) AS total_revenue
FROM sales
GROUP BY category
ORDER BY total_revenue DESC
"""
df_2a = pd.read_sql_query(query_2a, conn)
df_2a

      category  total_revenue
0  electronics     2826160.04
1     clothing     1261966.80
2   home goods      970427.95
3    groceries      705730.84
4         toys      315529.51

**2b.** Write a query that computes average `units_sold` per `store`, but only shows stores where the average exceeds 50 (use `HAVING`).

In [10]:
# TODO 2b
query_2b = """
SELECT store, AVG(units_sold) AS avg_units
FROM sales
GROUP BY store
HAVING AVG(units_sold) > 50
"""
df_2b = pd.read_sql_query(query_2b, conn)
df_2b

      store  avg_units
0    Albany  59.795156
1      Rome  60.604106
2  Syracuse  60.764585
3     Utica  62.260020

---
## Part 3 — Joins (25%)

**3a.** Write an `INNER JOIN` query between `sales` and `stores` that returns `store`, `category`, `revenue`, and `region` for the first 10 rows.

In [11]:
# TODO 3a
query_3a = """
SELECT s.store, s.category, s.revenue, st.region
FROM sales AS s
INNER JOIN stores AS st ON s.store = st.store
LIMIT 10
"""
df_3a = pd.read_sql_query(query_3a, conn)
df_3a

      store     category  revenue      region
0      Rome         toys   402.50  Central NY
1  Syracuse  electronics  3154.00  Central NY
2     Utica   home goods  1299.06  Central NY
3  Syracuse  electronics  5114.40  Central NY
4  Syracuse         toys   147.10  Central NY
5     Utica  electronics  3531.06  Central NY
6      Rome    groceries   807.54  Central NY
7     Utica   home goods   921.62  Central NY
8     Utica    groceries   631.80  Central NY
9      Rome    groceries   839.70  Central NY

**3b.** Write a `LEFT JOIN` query starting from `stores`, and print only the row(s) where there is no matching sale (hint: use `IS NULL`).

In [12]:
# TODO 3b
query_3b = """
SELECT st.store, st.region
FROM stores AS st
LEFT JOIN sales AS s ON st.store = s.store
WHERE s.store IS NULL
"""
df_3b = pd.read_sql_query(query_3b, conn)
df_3b

         store         region
0  Plattsburgh  North Country

**3c.** Write a query that joins `sales` and `stores`, then computes total `revenue` per `region`, sorted highest to lowest.

In [13]:
# TODO 3c
query_3c = """
SELECT st.region, SUM(s.revenue) AS total_revenue
FROM sales AS s
INNER JOIN stores AS st ON s.store = st.store
GROUP BY st.region
ORDER BY total_revenue DESC
"""
df_3c = pd.read_sql_query(query_3c, conn)
df_3c

             region  total_revenue
0        Central NY     4602739.67
1  Capital District     1477075.47

---
## Part 4 — SQL + pandas Integration (20%)

**4a.** Using a **parameterized query** (a `?` placeholder, not an f-string), write a query that returns all rows from `sales` for a store of your choice. Store the store name in a variable first, then pass it via `params=`.

In [14]:
# TODO 4a
selected_store = "Utica"

query_4a = "SELECT * FROM sales WHERE store = ?"
df_4a = pd.read_sql_query(query_4a, conn, params=(selected_store,))
df_4a

                     date  store  units_sold  revenue     category
0     2025-12-21 00:00:00  Utica        42.0  1299.06   home goods
1     2025-05-07 00:00:00  Utica        39.0  3531.06  electronics
2     2025-05-22 00:00:00  Utica        29.0   921.62   home goods
3     2025-11-26 00:00:00  Utica       108.0   631.80    groceries
4     2025-05-14 00:00:00  Utica        64.0  1578.24     clothing
...                   ...    ...         ...      ...          ...
1018  2025-12-10 00:00:00  Utica        28.0   900.48   home goods
1019  2025-10-21 00:00:00  Utica       118.0   790.60    groceries
1020  2025-08-25 00:00:00  Utica        56.0  1808.24   home goods
1021  2025-11-30 00:00:00  Utica        30.0   482.10         toys
1022  2025-03-25 00:00:00  Utica        23.0  2194.20  electronics

[1023 rows x 5 columns]

**4b.** Using the result from 4a, continue in pandas: compute the total `revenue` for that store using pandas (not SQL), and confirm it matches what you'd get by summing the `revenue` column directly from your query result.

In [15]:
# TODO 4b

pandas_total_revenue = df_4a["revenue"].sum()

print(f"Total revenue for {selected_store} (pandas): ${pandas_total_revenue:,.2f}")

Total revenue for Utica (pandas): $1,562,319.71

**4c.** Create a small summary DataFrame of your choice (e.g., total revenue per category) and save it into the database as a new table called `my_summary` using `.to_sql()`. Then query it back to confirm it was saved correctly.

In [16]:
# TODO 4c
# Create summary DataFrame in pandas
my_summary = sales_summary = df_2a.copy()

# Save into SQLite database as a new table 'my_summary'
my_summary.to_sql("my_summary", conn, if_exists="replace", index=False)

# Query back to verify
df_verify = pd.read_sql_query("SELECT * FROM my_summary", conn)
df_verify

      category  total_revenue
0  electronics     2826160.04
1     clothing     1261966.80
2   home goods      970427.95
3    groceries      705730.84
4         toys      315529.51

---
## Part 5 — Written Reflection (15%)

Answer each question in 1–3 sentences, in this markdown cell.

**5a.** In Part 3b, you found the store with no matching sales. Why does an `INNER JOIN` fail to show this store at all, while a `LEFT JOIN` does?

*Your answer here:*

An INNER JOIN requires a matching key in both tables, so any store (like Plattsburgh) without corresponding records in the sales table is completely dropped from the result. A LEFT JOIN retains all records from the left table (stores), filling in NULL for the missing columns from the right table (sales), which allows unmatched stores to appear.

**5b.** Why is a parameterized query (Part 4a) generally a better habit than building a query with an f-string, even for a class assignment where there's no real security risk?

*Your answer here:*

Parameterized queries automatically escape input values, preventing SQL injection vulnerabilities and formatting errors (such as unescaped single quotes in text). Using placeholders (?) builds good security and coding habits that apply seamlessly to production applications where user input cannot be trusted.

---
### AI Use Disclosure

*If you used an AI tool (Claude, ChatGPT, GitHub Copilot, etc.) for any part of this assignment, briefly state where and how below, and how you verified the result. If you did not use any AI tool, write "No AI tools were used."*

*Your answer here:*

No AI tools were used.

In [17]:
conn.close()